## Importing some essential libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf



## importing dataset

In [2]:
df=pd.read_csv('loan_data_set.csv')
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [3]:
df.shape

(614, 13)

In [4]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

## taking care of missing values


In [5]:
df[['Dependents','Gender','Married','Self_Employed']]=df[['Dependents','Gender','Married','Self_Employed']].fillna(method='ffill')

In [6]:
df[['LoanAmount','Loan_Amount_Term','Credit_History']]=df[['LoanAmount','Loan_Amount_Term','Credit_History']].fillna(df[['Dependents','LoanAmount','Loan_Amount_Term','Credit_History']].mean())


In [7]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

## Encoding categorical columns using one hot encoding and label encoding

applying label encoding to gender,married,education,self_employed,property_area and loan_status

In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [9]:
df.Gender=le.fit_transform(df.Gender)
df.Married=le.fit_transform(df.Married)
df.Education=le.fit_transform(df.Education)
df.Self_Employed=le.fit_transform(df.Self_Employed)
df.Property_Area=le.fit_transform(df.Property_Area)
df.Loan_Status=le.fit_transform(df.Loan_Status)
df.Dependents=le.fit_transform(df.Dependents)


In [10]:
df

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0    LP001002       1        0           0          0              0   
1    LP001003       1        1           1          0              0   
2    LP001005       1        1           0          0              1   
3    LP001006       1        1           0          1              0   
4    LP001008       1        0           0          0              0   
..        ...     ...      ...         ...        ...            ...   
609  LP002978       0        0           0          0              0   
610  LP002979       1        1           3          0              0   
611  LP002983       1        1           1          0              0   
612  LP002984       1        1           2          0              0   
613  LP002990       0        0           0          0              1   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0  146.412162             360.0   
1               4583             1508.0  128.000000             360.0   
2               3000                0.0   66.000000             360.0   
3               2583             2358.0  120.000000             360.0   
4               6000                0.0  141.000000             360.0   
..               ...                ...         ...               ...   
609             2900                0.0   71.000000             360.0   
610             4106                0.0   40.000000             180.0   
611             8072              240.0  253.000000             360.0   
612             7583                0.0  187.000000             360.0   
613             4583                0.0  133.000000             360.0   

     Credit_History  Property_Area  Loan_Status  
0               1.0              2            1  
1               1.0              0            0  
2               1.0              2            1  
3               1.0              2            1  
4               1.0              2            1  
..              ...            ...          ...  
609             1.0              0            1  
610             1.0              0            1  
611             1.0              2            1  
612             1.0              2            1  
613             0.0              1            0  

[614 rows x 13 columns]

## split our dataset into dependent nd independent variable and get our test nd train sets

In [11]:
x=df.drop(['Loan_Status','Loan_ID'],axis=1).values
y=df.Loan_Status.values

In [12]:
x

array([[  1.,   0.,   0., ..., 360.,   1.,   2.],
       [  1.,   1.,   1., ..., 360.,   1.,   0.],
       [  1.,   1.,   0., ..., 360.,   1.,   2.],
       ...,
       [  1.,   1.,   1., ..., 360.,   1.,   2.],
       [  1.,   1.,   2., ..., 360.,   1.,   2.],
       [  0.,   0.,   0., ..., 360.,   0.,   1.]])

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [14]:
x_train

array([[  1.        ,   1.        ,   1.        , ..., 360.        ,
          0.84219858,   2.        ],
       [  1.        ,   1.        ,   1.        , ..., 360.        ,
          1.        ,   2.        ],
       [  0.        ,   0.        ,   0.        , ..., 360.        ,
          1.        ,   0.        ],
       ...,
       [  1.        ,   1.        ,   1.        , ..., 360.        ,
          0.        ,   1.        ],
       [  0.        ,   0.        ,   0.        , ..., 360.        ,
          0.84219858,   0.        ],
       [  1.        ,   0.        ,   0.        , ..., 360.        ,
          1.        ,   0.        ]])

Now we do some feature selection so as to reduce the dimensionality of this dataset,


## Performming  dimensionality Reduction(feature_selection)using LDA

In [15]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda=LDA(n_components=1)
x_train=lda.fit_transform(x_train,y_train)
x_test=lda.transform(x_test)

In [16]:
x_train

array([[-0.11272482],
       [-0.85408856],
       [-0.12411714],
       [-0.2205691 ],
       [-0.71811918],
       [-0.5759762 ],
       [-0.6414875 ],
       [-0.37766296],
       [ 0.03085989],
       [-0.80786594],
       [-0.75500672],
       [-0.62612096],
       [-0.47059974],
       [-0.76895951],
       [-0.43572205],
       [-0.62545322],
       [-0.75760387],
       [-0.27611625],
       [-0.26110361],
       [-0.22427562],
       [ 2.93402018],
       [-0.72610508],
       [-0.05077591],
       [-0.01105611],
       [-0.09049432],
       [-0.69883855],
       [-0.6433415 ],
       [ 0.0106223 ],
       [ 0.01692396],
       [-0.4862192 ],
       [-0.70873569],
       [-0.1920119 ],
       [-0.28992789],
       [-0.21500596],
       [-0.6332145 ],
       [ 2.61568493],
       [ 3.29810301],
       [-0.27949295],
       [-0.23863895],
       [-0.56378878],
       [-0.62293821],
       [-0.40495212],
       [-0.20390257],
       [-0.87009276],
       [-0.64882163],
       [-0

## trainning our models with these dataset using kfold validation

In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score


In [18]:
cross_val_score(LogisticRegression(),x_train,y_train,cv=5)

array([0.80808081, 0.87755102, 0.82653061, 0.78571429, 0.78571429])

In [19]:
cross_val_score(SVC(kernel='rbf'),x_train,y_train,cv=5)

array([0.80808081, 0.86734694, 0.82653061, 0.78571429, 0.78571429])

In [20]:
cross_val_score(DecisionTreeClassifier(),x_train,y_train,cv=5)

array([0.71717172, 0.7244898 , 0.74489796, 0.62244898, 0.66326531])

In [21]:
cross_val_score(RandomForestClassifier(n_estimators=100),x_train,y_train,cv=5)

array([0.71717172, 0.7244898 , 0.74489796, 0.62244898, 0.66326531])

from this you can see that LogisticRegression  is the best 

# our model


In [22]:
model=SVC(kernel='rbf')
model.fit(x_train,y_train)

SVC()

## prediction

In [23]:
y_pred=model.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1])

### model evaluation

In [24]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm=confusion_matrix(y_pred,y_test)
score=accuracy_score(y_pred,y_test)
cm

array([[12,  1],
       [24, 86]], dtype=int64)

In [25]:
score

0.7967479674796748

### save model

In [26]:
import pickle
pickle.dump(model,open('Model_Classifier','wb'))

### load the model and use it for singe prediction

In [27]:
model=pickle.load(open('Model_Classifier','rb'))

In [28]:
model.predict(lda.transform([[1,0,0,0,0,5849,0.0,146.4126162,360.0,1.0,0]]))

array([1])